#!/bin/zsh
# claudew completion setup for zsh
# This file is installed to ~/.claudew/completion.zsh by 'claudew install-shell'

# Add completion directory to fpath
fpath=(~/.zsh/completion $fpath)

# Source the completion function directly
# The _claudew file is generated by Cobra and contains the completion logic
source ~/.zsh/completion/_claudew

# Register the completion function
compdef _claudew claudew
