#!/bin/bash
# claudew completion setup for bash
# This file is installed to ~/.claudew/completion.bash by 'claudew install-shell'

# Source the bash completion file generated by Cobra
source ~/.claudew-completion.bash
